import {it,expect} from 'vitest';
import {createSession,choose,veto,undo,type Session} from './tournament';
const ids=Array.from({length:12},(_,i)=>String(i));
const vote=(s:Session)=>choose(s,{matchId:s.pending!.id,winnerId:s.pending!.leftId});
it('empty groups and locked group vetoes never borrow qualifiers or resurrect eliminated players',()=>{
 let s=createSession({imageIds:ids,targetK:1,mode:'groups',seed:1});s=veto(s,s.groups[0].members);s=veto(s,s.groups[1].members.slice(1));let limit=0;while(s.pending?.kind==='group'||s.pending?.kind==='tie'){if(++limit>50)throw Error('loop');s=vote(s);}expect(s.groupsLocked).toBe(true);expect(s.groups[0].qualifiers).toEqual([]);expect(s.groups[1].qualifiers).toHaveLength(1);const remaining=s.config.imageIds.filter(id=>!s.vetoed.includes(id));const before=s;s=veto(s,remaining);expect(s.completed).toBe(true);expect(s.ranked).toHaveLength(0);expect(undo(s).groups).toEqual(before.groups);
});
it('veto during cyclic tiebreak clears that group answers and recalculates qualifying boundaries',()=>{let s=createSession({imageIds:ids.slice(0,6),targetK:1,mode:'groups',seed:17});while(s.pending?.kind==='group'){const m=s.pending,g=s.groups[m.group!].members,a=g.indexOf(m.leftId),b=g.indexOf(m.rightId);s=choose(s,{matchId:m.id,winnerId:(a+1)%3===b?m.leftId:m.rightId});}expect(s.pending?.kind).toBe('tie');s=vote(s);const gi=s.pending!.group!,before=s;s=veto(s,[s.groups[gi].members[0]]);expect(s.groups[gi].ties).toEqual({});expect(undo(s).groups).toEqual(before.groups);let n=0;while(s.pending){if(++n>20)throw Error('loop');s=vote(s);}expect(s.ranked).toHaveLength(1);});
it('double final reset and its undo preserve the first-final matchup, without caching votes',()=>{let s=createSession({imageIds:ids.slice(0,5),targetK:1,mode:'double',seed:42});while(s.pending!.label!=='总决赛')s=vote(s);const before=s,m=s.pending!;s=choose(s,{matchId:m.id,winnerId:m.rightId});expect(s.pending!.label).toBe('最终决胜局');expect(undo(s).pending?.leftId).toBe(before.pending?.leftId);expect(undo(s).graph[s.resetIndex!].winner).toBeUndefined();expect(s.losses[m.leftId]).toBe(1);s=veto(s,[m.leftId,m.rightId]);expect(s.ranked).toHaveLength(0);expect(s.vetoed).toHaveLength(2);expect(s.config.imageIds.length>s.vetoed.length).toBe(true);});
it('maintains group point totals immediately even while later fixtures remain unplayed',()=>{let s=createSession({imageIds:ids.slice(0,8),targetK:1,mode:'groups',seed:9});for(let i=0;i<4;i++)s=vote(s);const scores=s.groups[0].points;expect(Object.values(scores).reduce((a,b)=>a+b,0)).toBe(4);});
