import { describe,it,expect } from 'vitest';
import {createSession,choose,veto,undo,displayPair,minimum,groupCount,estimate,modes,type Session,type TournamentMode} from './tournament';
const ids=(n:number)=>Array.from({length:n},(_,i)=>`${i}`.padStart(3,'0'));
function run(s:Session,chooser=(s:Session)=>[s.pending!.leftId,s.pending!.rightId].sort()[0]) {let i=0;while(s.pending){if(++i>3000)throw Error('loop');s=choose(s,{matchId:s.pending.id,winnerId:chooser(s)});}return s;}
const start=(mode:TournamentMode,n=8)=>createSession({mode,imageIds:ids(n),targetK:mode==='ranking'?3:1,seed:29});
describe('five modes and referee',()=>{
 it('plays double elimination for odd and even brackets; only two losses eliminate normally',()=>{for(let n=4;n<=65;n++){for(const reset of [false,true]){let s=start('double',n);const seen=new Set<string>();let guard=0;while(s.pending){if(++guard>2*n)throw Error('loop');const m=s.pending;expect((s.losses[m.leftId]??0)<2&&(s.losses[m.rightId]??0)<2).toBe(true);seen.add(m.leftId);seen.add(m.rightId);const winner=m.label==='总决赛'&&reset?m.rightId:[m.leftId,m.rightId].sort()[0];s=choose(s,{matchId:m.id,winnerId:winner});}expect(s.history.length).toBeGreaterThanOrEqual(2*n-2);expect(s.history.length).toBeLessThanOrEqual(2*n-1);expect(seen.size).toBe(n);for(const id of ids(n).filter(id=>id!==s.ranked[0].imageId))expect(s.losses[id]).toBe(2);}}});
 it('gauntlet takes N-1 votes, switches reigns and never counts vetoes as wins',()=>{let s=start('gauntlet');s=choose(s,{matchId:s.pending!.id,winnerId:s.pending!.leftId});expect(s.streak).toBe(1);const before=s; s=veto(s,[s.pending!.rightId]);expect(s.streak).toBe(1);expect(displayPair(undo(s))).toEqual(displayPair(before));s=veto(s,[s.holder!]);expect(s.streak).toBe(0);expect(run(start('gauntlet')).history).toHaveLength(7);});
 it('all modes handle atomic double veto, empty outcomes, exact undo and no resurrection',()=>{for(const mode of modes){let s=start(mode);const before=s;s=veto(s,[s.pending!.leftId,s.pending!.rightId]);expect(s.events).toHaveLength(1);expect(s.history).toHaveLength(0);expect(undo(s).ranked).toEqual(before.ranked);expect(displayPair(undo(s))).toEqual(displayPair(before));s=veto(s,s.config.imageIds.filter(id=>!s.vetoed.includes(id)));expect(s.completed).toBe(true);expect(s.ranked).toEqual([]);expect(s.pending).toBeNull();expect(undo(s).vetoed).toHaveLength(2);}});
 it('ranking veto removes selected champion and exactly fills surviving Top K across seeds',()=>{for(let seed=0;seed<60;seed++){let s=run(createSession({mode:'ranking',imageIds:ids(17),targetK:10,seed}));for(const id of ['000','002','006','009','014']){s=run(veto(s,[id]));expect(s.ranked.map(r=>r.imageId)).toEqual(ids(17).filter(x=>!s.vetoed.includes(x)).slice(0,10));}s=run(veto(s,ids(17).filter(x=>!s.vetoed.includes(x)&&x!=='016')));expect(s.ranked).toEqual([{imageId:'016',rank:1}]);}});
 it('a champion veto never promotes a previously eliminated image outside ranking',()=>{for(const mode of modes.filter(m=>m!=='ranking')){const s=run(start(mode)),next=veto(s,[s.ranked[0].imageId]);expect(next.completed).toBe(true);expect(next.ranked).toEqual([]);expect(next.vetoed).toHaveLength(1);expect(undo(next).ranked).toEqual(s.ranked);}});
 it('groups are balanced, power of two, and match estimates without ties',()=>{for(let n=6;n<=64;n++){const initial=start('groups',n);expect(initial.groups.length).toBe(groupCount(n));expect(initial.groups.every(g=>g.members.length>=3&&g.members.length<=6)).toBe(true);const s=run(initial);expect(s.history.length).toBe(estimate('groups',n));expect(s.ranked[0].imageId).toBe('000');expect(s.groupsLocked).toBe(true);}});
 it('cyclic group preferences enter finite fresh tiebreaks',()=>{let s=start('groups',6);s=run(s,current=>{const m=current.pending!;if(m.kind!=='group')return m.leftId;const members=current.groups[m.group!].members,a=members.indexOf(m.leftId),b=members.indexOf(m.rightId);return (a+1)%3===b?m.leftId:m.rightId;});expect(s.history.filter(d=>d.label?.includes('加赛')).length).toBeGreaterThanOrEqual(4);expect(s.history.length).toBeLessThanOrEqual(15);});
 it('group veto voids points before locking, but preserves locked standings afterward',()=>{let s=start('groups',6);const m=s.pending!;s=choose(s,{matchId:m.id,winnerId:m.leftId});s=veto(s,[m.leftId]);expect(s.groups[0].points[m.leftId]).toBeUndefined();expect(s.history).toHaveLength(1);s=run(s);const points=structuredClone(s.groups.map(g=>g.points));s=veto(s,[s.ranked[0].imageId]);expect(s.groups.map(g=>g.points)).toEqual(points);});
 it('mixed decisions terminate, undo all phases and reject stale actions',()=>{for(const mode of modes)for(let seed=0;seed<15;seed++){let s=createSession({mode,imageIds:ids(17),targetK:mode==='ranking'?6:1,seed}),guard=0;while(s.pending){if(++guard>1500)throw Error('loop');const prev=s,m=s.pending;const next=guard%5===0?veto(s,[m.leftId,m.rightId]):choose(s,{matchId:m.id,winnerId:guard%2?m.leftId:m.rightId});const back=undo(next);expect(back.ranked).toEqual(prev.ranked);expect(back.vetoed).toEqual(prev.vetoed);expect(displayPair(back)).toEqual(displayPair(prev));expect(()=>veto(back,[m.leftId],prev.revision)).toThrow('过期');s=next;}expect(s.ranked.every(r=>!s.vetoed.includes(r.imageId))).toBe(true);}});
 it('new modes enforce minimum counts and expected group examples',()=>{for(const mode of ['gauntlet','double','groups'] as const)expect(()=>start(mode,minimum[mode]-1)).toThrow();expect([6,8,9,12,16].map(n=>estimate('groups',n))).toEqual([9,15,19,19,31]);});
});
